"""avisos de recordatorios

Calendario de pagos, etapa 2 (1.5.0, ver 0030): los avisos.
- `reminder_cycles`: `snoozed_until` ("Mas tarde") y lo que el servidor ya aviso
  (`alerts_sent`, `followup_sent_on`), para no repetirlo.
- `notifications.meta`: de que vencimiento es un aviso de recordatorio (los
  botones del push lo necesitan).
- `users.snooze_default`: hasta cuando calla el boton "Mas tarde" del aviso.
- `reminder_action_tokens`: los permisos de un solo uso de esos botones (el
  service worker no tiene la sesion). No se sincroniza.

Aditivo (0012): columnas opcionales y una tabla nueva.

Revision ID: 2735ffa49768
Revises: f8b81f3fc509
Create Date: 2026-10-07 13:46:59.033583

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2735ffa49768"
down_revision: str | None = "f8b81f3fc509"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reminder_action_tokens",
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("reminder_id", sa.UUID(), nullable=False),
        sa.Column("nominal_date", sa.Date(), nullable=False),
        sa.Column("expires_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("used_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["reminder_id"],
            ["reminders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.add_column(
        "notifications",
        sa.Column(
            "meta", postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column(
        "reminder_cycles",
        sa.Column("snoozed_until", postgresql.TIMESTAMP(timezone=True), nullable=True),
    )
    op.add_column(
        "reminder_cycles",
        sa.Column(
            "alerts_sent", postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column("reminder_cycles", sa.Column("followup_sent_on", sa.Date(), nullable=True))
    op.add_column("users", sa.Column("snooze_default", sa.Text(), nullable=True))
    op.create_check_constraint(
        "users_snooze_default_chk",
        "users",
        "snooze_default IS NULL OR snooze_default IN ('1h','3h','manana')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_snooze_default_chk", "users", type_="check")
    op.drop_column("users", "snooze_default")
    op.drop_column("reminder_cycles", "followup_sent_on")
    op.drop_column("reminder_cycles", "alerts_sent")
    op.drop_column("reminder_cycles", "snoozed_until")
    op.drop_column("notifications", "meta")
    op.drop_table("reminder_action_tokens")
    # ### end Alembic commands ###
