"""users apariencia (theme_id, theme_custom, color_scheme)

Revision ID: 4a1f37a24b28
Revises: adfc9f706be4
Create Date: 2026-08-30 15:18:06.774097

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4a1f37a24b28"
down_revision: str | None = "adfc9f706be4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("theme_id", sa.Text(), server_default=sa.text("'default'"), nullable=False),
    )
    op.add_column(
        "users", sa.Column("theme_custom", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    op.add_column(
        "users",
        sa.Column("color_scheme", sa.Text(), server_default=sa.text("'system'"), nullable=False),
    )
    op.create_check_constraint(
        "users_color_scheme_chk", "users", "color_scheme IN ('light','dark','system')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_color_scheme_chk", "users", type_="check")
    op.drop_column("users", "color_scheme")
    op.drop_column("users", "theme_custom")
    op.drop_column("users", "theme_id")
    # ### end Alembic commands ###
