"""settlement_id en transactions

Revision ID: 5490326504d0
Revises: ea50fb792ff6
Create Date: 2026-09-26 00:29:22.864610

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5490326504d0"
down_revision: str | None = "ea50fb792ff6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transactions", sa.Column("settlement_id", sa.UUID(), nullable=True))
    op.create_foreign_key(None, "transactions", "settlements", ["settlement_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "transactions", type_="foreignkey")
    op.drop_column("transactions", "settlement_id")
    # ### end Alembic commands ###
