"""sobres: categories rollover default_budget, budgets sin period, checks tx

Revision ID: 5c0af955cf8e
Revises: fcf7cf6327ac
Create Date: 2026-08-31 01:16:49.641901

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5c0af955cf8e"
down_revision: str | None = "fcf7cf6327ac"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("budgets_uniq"),
        table_name="budgets",
        postgresql_where="(deleted_at IS NULL)",
        postgresql_nulls_not_distinct=True,
    )
    op.create_index(
        "budgets_uniq",
        "budgets",
        ["owner_id", "group_id", "category_id", "period_start"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
        postgresql_nulls_not_distinct=True,
    )
    op.drop_constraint(op.f("budgets_period_chk"), "budgets", type_="check")
    op.drop_column("budgets", "period")
    op.drop_column("budgets", "rollover")
    op.add_column(
        "categories",
        sa.Column("rollover", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    op.add_column("categories", sa.Column("default_budget", sa.BigInteger(), nullable=True))
    op.create_check_constraint(
        "tx_categoria_obligatoria_chk",
        "transactions",
        "kind = 'transfer' OR status IN ('pending', 'rejected') OR category_id IS NOT NULL",
    )
    op.create_check_constraint(
        "tx_transfer_sin_categoria_chk", "transactions", "kind <> 'transfer' OR category_id IS NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("tx_transfer_sin_categoria_chk", "transactions", type_="check")
    op.drop_constraint("tx_categoria_obligatoria_chk", "transactions", type_="check")
    op.drop_column("categories", "default_budget")
    op.drop_column("categories", "rollover")
    op.add_column(
        "budgets",
        sa.Column(
            "rollover",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "budgets",
        sa.Column(
            "period",
            sa.TEXT(),
            server_default=sa.text("'monthly'::text"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_check_constraint(
        op.f("budgets_period_chk"),
        "budgets",
        "period = ANY (ARRAY['weekly'::text, 'monthly'::text, 'yearly'::text])",
    )
    op.drop_index(
        "budgets_uniq",
        table_name="budgets",
        postgresql_where=sa.text("deleted_at IS NULL"),
        postgresql_nulls_not_distinct=True,
    )
    op.create_index(
        op.f("budgets_uniq"),
        "budgets",
        ["owner_id", "group_id", "category_id", "period", "period_start"],
        unique=True,
        postgresql_where="(deleted_at IS NULL)",
        postgresql_nulls_not_distinct=True,
    )
    # ### end Alembic commands ###
