"""drop sync_state y sync_log (PowerSync los reemplaza)

Revision ID: 84bb08556db4
Revises: 4a6d083495f0
Create Date: 2026-09-03 00:00:42.682880

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "84bb08556db4"
down_revision: str | None = "4a6d083495f0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sync_state")
    op.drop_index(op.f("sync_log_user_idx"), table_name="sync_log")
    op.drop_table("sync_log")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sync_log",
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("device_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("entity", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("entity_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("operation", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "applied_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.CheckConstraint(
            "operation = ANY (ARRAY['insert'::text, 'update'::text, 'delete'::text])",
            name=op.f("sync_log_op_chk"),
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("sync_log_user_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("sync_log_pkey")),
    )
    op.create_index(
        op.f("sync_log_user_idx"),
        "sync_log",
        ["user_id", sa.literal_column("applied_at DESC")],
        unique=False,
    )
    op.create_table(
        "sync_state",
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("device_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "last_synced_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("sync_state_user_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("sync_state_pkey")),
        sa.UniqueConstraint(
            "user_id",
            "device_id",
            name=op.f("sync_state_uniq"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    # ### end Alembic commands ###
