"""quitar default_budget de categories

Revision ID: 92b5f6feb74b
Revises: 5c0af955cf8e
Create Date: 2026-08-31 01:53:49.981626

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "92b5f6feb74b"
down_revision: str | None = "5c0af955cf8e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("categories", "default_budget")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "categories", sa.Column("default_budget", sa.BIGINT(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
