"""budgets_uniq parcial nulls not distinct

Revision ID: adfc9f706be4
Revises: f25495000839
Create Date: 2026-08-30 14:50:54.084747

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "adfc9f706be4"
down_revision: str | None = "f25495000839"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("budgets_uniq"), "budgets", type_="unique")
    op.create_index(
        "budgets_uniq",
        "budgets",
        ["owner_id", "group_id", "category_id", "period", "period_start"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
        postgresql_nulls_not_distinct=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "budgets_uniq",
        table_name="budgets",
        postgresql_where=sa.text("deleted_at IS NULL"),
        postgresql_nulls_not_distinct=True,
    )
    op.create_unique_constraint(
        op.f("budgets_uniq"),
        "budgets",
        ["owner_id", "group_id", "category_id", "period", "period_start"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
