"""cuenta conjunta y paid_from_group

Revision ID: beb913b6e950
Revises: 0e9b8b99d2f7
Create Date: 2026-09-25 23:32:59.914485

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "beb913b6e950"
down_revision: str | None = "0e9b8b99d2f7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("accounts", "owner_id", existing_type=sa.UUID(), nullable=True)
    op.add_column(
        "transactions",
        sa.Column("paid_from_group", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transactions", "paid_from_group")
    op.alter_column("accounts", "owner_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
