"""payment_methods sort_order

Revision ID: d64c41b7e606
Revises: 84bb08556db4
Create Date: 2026-09-04 00:14:22.831460

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d64c41b7e606"
down_revision: str | None = "84bb08556db4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "payment_methods",
        sa.Column("sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("payment_methods", "sort_order")
    # ### end Alembic commands ###
