"""settlement account y medio de pago

Revision ID: ea50fb792ff6
Revises: beb913b6e950
Create Date: 2026-09-25 23:55:37.852845

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ea50fb792ff6"
down_revision: str | None = "beb913b6e950"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("settlements", sa.Column("account_id", sa.UUID(), nullable=True))
    op.add_column("settlements", sa.Column("payment_method_id", sa.UUID(), nullable=True))
    op.create_foreign_key(None, "settlements", "payment_methods", ["payment_method_id"], ["id"])
    op.create_foreign_key(None, "settlements", "accounts", ["account_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "settlements", type_="foreignkey")
    op.drop_constraint(None, "settlements", type_="foreignkey")
    op.drop_column("settlements", "payment_method_id")
    op.drop_column("settlements", "account_id")
    # ### end Alembic commands ###
