"""pma_uniq parcial (respeta borrado logico)

Revision ID: f25495000839
Revises: 15fa3148ff95
Create Date: 2026-08-30 14:35:32.276530

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f25495000839"
down_revision: str | None = "15fa3148ff95"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("pma_uniq"), "payment_method_accounts", type_="unique")
    op.create_index(
        "pma_uniq",
        "payment_method_accounts",
        ["payment_method_id", "currency"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "pma_uniq",
        table_name="payment_method_accounts",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_unique_constraint(
        op.f("pma_uniq"),
        "payment_method_accounts",
        ["payment_method_id", "currency"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
