"""recordatorios

Calendario de pagos (1.5.0, ver 0030): `reminders` (que pagar y la regla de
repeticion) y `reminder_cycles` (lo que paso con cada vencimiento: pagado u
omitido). Las fechas de los vencimientos no se guardan: se calculan con la regla
(services/repeticion.py). Un ciclo tiene fila solo cuando se responde, con id
determinista, asi que no hay nada que llenar para los recordatorios existentes:
no hay ninguno.

Aditivo (0012): tablas nuevas, un cliente viejo no las conoce y las ignora.

Revision ID: f8b81f3fc509
Revises: 05da15d85869
Create Date: 2026-10-04 13:22:21.587031

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f8b81f3fc509"
down_revision: str | None = "05da15d85869"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reminders",
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("template_id", sa.UUID(), nullable=True),
        sa.Column("freq", sa.Text(), nullable=False),
        sa.Column("interval_count", sa.SmallInteger(), server_default=sa.text("1"), nullable=False),
        sa.Column("weekdays", sa.SmallInteger(), nullable=True),
        sa.Column("month_mode", sa.Text(), nullable=True),
        sa.Column("month_day", sa.SmallInteger(), nullable=True),
        sa.Column("month_week", sa.SmallInteger(), nullable=True),
        sa.Column("month_weekday", sa.SmallInteger(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("until_date", sa.Date(), nullable=True),
        sa.Column("count", sa.SmallInteger(), nullable=True),
        sa.Column("weekend_shift", sa.Text(), nullable=False),
        sa.Column("track_from", sa.Date(), nullable=False),
        sa.Column(
            "alerts",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text('\'[{"days_before": 0, "time": "09:00"}]\'::jsonb'),
            nullable=False,
        ),
        sa.Column("followup_days", sa.SmallInteger(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.CheckConstraint(
            "freq IN ('once','daily','weekly','monthly','yearly')", name="reminders_freq_chk"
        ),
        sa.CheckConstraint(
            "month_mode IS NULL OR month_mode IN ('day','weekday')", name="reminders_month_mode_chk"
        ),
        sa.CheckConstraint(
            "weekend_shift IN ('none','next','previous')", name="reminders_weekend_shift_chk"
        ),
        sa.CheckConstraint("count IS NULL OR count >= 1", name="reminders_count_chk"),
        sa.CheckConstraint("count IS NULL OR until_date IS NULL", name="reminders_un_solo_fin_chk"),
        sa.CheckConstraint(
            "followup_days IS NULL OR followup_days BETWEEN 0 AND 30", name="reminders_followup_chk"
        ),
        sa.CheckConstraint("interval_count BETWEEN 1 AND 99", name="reminders_interval_chk"),
        sa.CheckConstraint(
            "month_day IS NULL OR month_day BETWEEN 1 AND 31", name="reminders_month_day_chk"
        ),
        sa.CheckConstraint(
            "month_week IS NULL OR month_week IN (1, 2, 3, 4, -1)", name="reminders_month_week_chk"
        ),
        sa.CheckConstraint(
            "month_weekday IS NULL OR month_weekday BETWEEN 0 AND 6",
            name="reminders_month_weekday_chk",
        ),
        sa.CheckConstraint(
            "weekdays IS NULL OR weekdays BETWEEN 1 AND 127", name="reminders_weekdays_chk"
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["templates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "reminder_cycles",
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("reminder_id", sa.UUID(), nullable=False),
        sa.Column("nominal_date", sa.Date(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("answered_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("answered_by", sa.UUID(), nullable=True),
        sa.Column("transaction_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending','paid','skipped')", name="reminder_cycles_status_chk"
        ),
        sa.ForeignKeyConstraint(
            ["answered_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reminder_id"],
            ["reminders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "reminder_cycles_reminder_nominal_uniq",
        "reminder_cycles",
        ["reminder_id", "nominal_date"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "reminder_cycles_reminder_nominal_uniq",
        table_name="reminder_cycles",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("reminder_cycles")
    op.drop_table("reminders")
    # ### end Alembic commands ###
